image: node:lts-slim

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

stages:
  - build

build:
  stage: build
  script:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile --strict-peer-dependencies
    - pnpm run build

eslint:
  stage: build
  script:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile --strict-peer-dependencies
    - pnpm run test
